### ISSUE TITLE
`votecust` doesn't update "total_votes" in candidates table

### ISSUE THREAD

**Issue by jchung00** [eosdac/daccustodian#29]
Tested votecust and it doesn't seem like the candidates table gets updated. The votes table does get updated though. Is this normal?

**Comment by dallasjohnson** [comment]
What were the steps you followed for that? That seems to be working for all my tests but maybe you have found edge case that doesn't update the `total_votes` on candidates. My assertions around this involve checking the candidates before a valid `votecust` has been called then checking again after. Just to clarify, do you mean `custodians` or `candidates`? If it's custodians that is expected behaviour so that we have a snapshot of the total votes at the time `newperiod` was run to elect the candidates.

**Comment by jchung00** [comment]
Didn't run `newperiod`, closing this issue
