### ISSUE TITLE
This may be a local issue on my computer, but I can't seem to generate the abi file

### ISSUE THREAD

**Issue by lukestokes** [eosdac/daccustodian#41]
Both this:
```
eosio-abigen daccustodian.hpp -contract lukedaccusto -output output/jungle/daccustodian/daccustodian.abi 
```
and this:
```
eosio-cpp -DTOKENCONTRACT='"lukedactoken"' -DTRANSFER_DELAY=20 -o output/jungle/daccustodian/daccustodian.wasm daccustodian.cpp -abigen
```
create an abi file which is basically empty. Any idea what I'm doing wrong?

Thanks!

**Comment by lukestokes** [comment]
Hmm... just tried again with a fresh install and it worked so maybe it was just that I was using the wrong contract value. Closing for now.

**Comment by dallasjohnson** [comment]
Sorry @lukestokes for the slow response. I have bash scripts inside the 'output' folders for all the contract repos that will build the wasm and abi's for each targets (unit tests, jungle, and prod) since each may have slightly different compile time configurations. But they do depend on the compile tools to be installed and working correctly. Glad to hear you got it working.
